### ISSUE TITLE
Socket.io-react with create react app

### ISSUE THREAD

**Issue by ar5had** [PlatziDev/socket.io-react#5]
I am trying to use socket.io-react with `create-react-app`. I have attached node backend at port `3001` and `create-react-app` development server at port `3000`. 

My code looks like - 

``` js
// index.js
import {SocketProvider} from 'socket.io-react';
import io from 'socket.io-client';

import App from './components/app/App.js';
import React from 'react';
import ReactDOM from 'react-dom';

const socket = io('http://localhost:3001');
socket.on('message', msg => console.log(msg));

ReactDOM.render(
  <SocketProvider socket={socket}>
    <App />
  </SocketProvider>,
  document.getElementById('root')
);


```

``` js
// server.js
const app = require('express')();
const path = require('path');
const mongoose = require('mongoose');
const bodyParser = require('body-parser');
const socketServer = require('http').Server(app);
const io = require('socket.io')(socketServer);

const Stock = require('./models/stock.js');
const routes = require('./app/routes.js');

// loads all custom environments variables
if (process.env.NODE_ENV !== "production") {
  require('dotenv').config();
}

socketServer.listen(3002);
app.set('port', (process.env.PORT || 3001));

io.on('connection', function(socket) {
        console.log('a user connected, id ' + socket.id);
        socket.on('disconnect', function() {
            console.log('a user disconnected, id '  + socket.id);
        })
})

...
```

and I am getting the following error in console - 

``` js
GET http://localhost:3001/socket.io/?EIO=3&transport=polling&t=Ldg56In 404 (Not Found)
Request.create @ polling-xhr.js:261
Request @ polling-xhr.js:166
XHR.request @ polling-xhr.js:93
XHR.doPoll @ polling-xhr.js:123
Polling.poll @ polling.js:118
Polling.doOpen @ polling.js:63
Transport.open @ transport.js:80
Socket.open @ socket.js:240
Socket @ socket.js:119
Socket @ socket.js:29
Manager.open.Manager.connect @ manager.js:213
(anonymous) @ manager.js:527

localhost/:1 XMLHttpRequest cannot load http://localhost:3001/socket.io/?EIO=3&transport=polling&t=Ldg56In. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.

```
What should i do to make the setup work and what is the `process.env.SOCKET_URL`? 

Thanks!

**Comment by ar5had** [comment]
One more thing, if i need to access `socket` inside child components of `App`, do I need to wrap all such components into `SocketProvider` component ? 

Without wrapping `SocketProvider` component  around some child components of my app and importing `socketConnect`, I was able to get `socket` as prop. But for some element, all the refs of parent were removed.

Warning - 
``` 
Warning: Stateless function components cannot be given refs (See ref "panel" in SocketConnect created by App). Attempts to access this ref will fail.

```

**Comment by ar5had** [comment]
I know I should not use ref for stateless components but why doesn't my app throw error before adding socketConnect wrap on it ?

**Comment by sergiodxa** [comment]
`process.env.SOCKET_URL` is the URL for the socket.io server, in your case `http://localhost:3001`, I used the environment variable in the readme as an example, you can just write the url as you did.

The error you have it's because a CORS problem, try using the [cors](https://www.npmjs.com/package/cors) middleware in your express application.

About the second comment, the `SocketProvider` is just used to set the socket.io instance in the context, but you must use `socketConnect` to access that socket instance inside any component you want to. It's the same pattern used in [react-redux](https://github.com/reactjs/react-redux).

**Comment by ar5had** [comment]
@sergiodxa thanks for replying. I finally solved port issue.  Can you tell me why all the refs that were workin before using socket.io-react stopped working ?

**Comment by sergiodxa** [comment]
@arshdkhn1 I think it's because how `socketConnect` works. After applying the high order component what you use is a new component created by `socketConnect` and not your component.

You can check the code of the HOC here https://github.com/PlatziDev/socket.io-react/blob/master/lib/socket-connect.js to understand how it works.

**Comment by ar5had** [comment]
@sergiodxa thank you so much for all your help.
